services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER={{ project_name }}
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB={{ project_name }}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated
    restart: unless-stopped

  broker:
    image: "rabbitmq:alpine"
    restart: unless-stopped

  result:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
    restart: unless-stopped

  celery:
    build:
      dockerfile: backend/Dockerfile
      context: .
    command: celery --app={{ project_name }} worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
    restart: unless-stopped

volumes:
  dbdata:
    name: {{ project_name }}_dbdata
    external: true
